"""Release evidence pack model for ``saturnday.release``.

Defines the structured evidence artefact produced by a ``release-preflight``
run: per-check results, the full artefact inventory, disposition, diff summary,
and premium capability state.  Evidence is written as JSON + summary.md into a
run-specific subdirectory under ``.saturnday/evidence/release/{run_id}/``.

Typical usage::

    from saturnday.release.evidence import (
        ReleaseCheckResult,
        ReleaseEvidencePack,
        compute_release_disposition,
        write_release_evidence,
        RELEASE_SCHEMA_VERSION,
    )

    check_results = [ReleaseCheckResult(...), ...]
    disposition, reasons = compute_release_disposition(check_results)

    pack = ReleaseEvidencePack(
        schema_version=RELEASE_SCHEMA_VERSION,
        run_id=generate_release_run_id(),
        artefact_type="wheel",
        ...
        disposition=disposition,
        disposition_reasons=reasons,
        ...
    )
    evidence_path = write_release_evidence(pack, output_dir)
"""
from __future__ import annotations

import json
import logging
import os
import secrets
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Schema version
# ---------------------------------------------------------------------------

#: Bump when the serialised structure of :class:`ReleaseEvidencePack` changes
#: in a backward-incompatible way.
RELEASE_SCHEMA_VERSION: str = "1.0.0"

#: Canonical subdirectory name within the evidence root for release evidence.
#: Mirrors ``EVIDENCE_DIR_GUARD``, ``EVIDENCE_DIR_RUN``, etc. from
#: ``saturnday.shared.evidence_schema``.
EVIDENCE_DIR_RELEASE: str = "evidence/release"


# ---------------------------------------------------------------------------
# Per-check result
# ---------------------------------------------------------------------------


@dataclass
class ReleaseCheckResult:
    """Result of a single release-security check.

    Each check in the ``release-preflight`` pipeline produces exactly one
    :class:`ReleaseCheckResult`.  Downstream code aggregates these into a
    :class:`ReleaseEvidencePack` and calls :func:`compute_release_disposition`
    to derive the overall pass/warn/fail verdict.

    Attributes:
        name:          Human-readable check identifier, e.g. ``"source_map_blocker"``.
        rule_id:       Stable rule ID that is never reused, e.g. ``"REL-001"``.
        status:        One of ``"PASS"``, ``"FAIL"``, ``"WARN"``, ``"SKIPPED"``.
        severity:      One of ``"error"`` (blocks release), ``"warning"`` (advisory),
                       or ``"info"`` (informational only).
        findings:      List of individual finding dicts.  Each dict is check-specific
                       but should at minimum contain a ``"path"`` key.
        files_checked: Count of artefact files examined by this check.
        elapsed_s:     Wall-clock time in seconds taken by this check.
    """

    name: str
    rule_id: str
    status: str
    severity: str
    findings: list[dict[str, Any]] = field(default_factory=list)
    files_checked: int = 0
    elapsed_s: float = 0.0


# ---------------------------------------------------------------------------
# Evidence pack
# ---------------------------------------------------------------------------


@dataclass
class ReleaseEvidencePack:
    """Complete evidence for a ``release-preflight`` run.

    One instance is produced per invocation of the release-preflight
    orchestrator, regardless of how many checks ran.  Fields are designed
    so the JSON serialisation is both machine-readable and diff-friendly.

    Attributes:
        schema_version:         Schema version string; use
                                :data:`RELEASE_SCHEMA_VERSION`.
        run_id:                 Unique run identifier generated by
                                :func:`generate_release_run_id`.
        artefact_type:          One of ``"wheel"``, ``"sdist"``, ``"npm"``.
        artefact_path:          Absolute path to the inspected artefact.
        artefact_sha256:        Lowercase hex SHA-256 of the packed artefact.
        inventory:              Serialised :class:`~saturnday.release._types.ArtefactInventory`
                                as a plain dict (use ``dataclasses.asdict``).
        check_results:          Ordered list of per-check results.
        disposition:            Overall verdict: ``"PASS"``, ``"WARN"``, or ``"FAIL"``.
        disposition_reasons:    Human-readable explanation strings for non-PASS dispositions.
        baseline_artefact_path: Path to the baseline artefact used for diff comparison.
                                Empty string when no baseline was provided.
        release_diff:           Structured diff output; empty dict when no baseline.
        capability_state:       Premium capability state snapshot from
                                :func:`~saturnday.shared.evidence_schema.build_capability_state`.
                                Always recorded, even when premium is absent (golden rule).
        created_utc:            ISO 8601 UTC timestamp at pack creation time.
    """

    schema_version: str
    run_id: str
    artefact_type: str
    artefact_path: str
    artefact_sha256: str
    inventory: dict[str, Any]
    check_results: list[ReleaseCheckResult] = field(default_factory=list)
    disposition: str = "PASS"
    disposition_reasons: list[str] = field(default_factory=list)
    baseline_artefact_path: str = ""
    release_diff: dict[str, Any] = field(default_factory=dict)
    capability_state: dict[str, Any] = field(default_factory=dict)
    created_utc: str = ""

    def __post_init__(self) -> None:
        if not self.created_utc:
            self.created_utc = datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Run-ID generator
# ---------------------------------------------------------------------------


def generate_release_run_id() -> str:
    """Generate a unique, time-ordered run identifier.

    Format: ``release_{YYYYMMDDTHHMMSSZ}_{pid}_{hex4}``

    The UTC timestamp provides human-readable ordering; the PID disambiguates
    parallel invocations on the same second; the 4-character hex token provides
    collision resistance within a single PID.

    Returns:
        A run-ID string suitable for use as a directory name and JSON field.

    Example::

        >>> run_id = generate_release_run_id()
        >>> run_id.startswith("release_")
        True
    """
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    pid = os.getpid()
    token = secrets.token_hex(2)  # 4 hex chars
    return f"release_{ts}_{pid}_{token}"


# ---------------------------------------------------------------------------
# Disposition computation
# ---------------------------------------------------------------------------


def compute_release_disposition(
    check_results: list[ReleaseCheckResult],
) -> tuple[str, list[str]]:
    """Compute the overall release disposition from a list of check results.

    Disposition rules (applied in priority order):

    1. **FAIL** — any check with ``status == "FAIL"`` and ``severity == "error"``
       is present.  This is a hard block; the release must not proceed.
    2. **WARN** — any check with ``status == "FAIL"`` and ``severity == "warning"``
       is present, or any check with ``status == "WARN"`` regardless of severity.
       Advisory; release may proceed with human acknowledgement.
    3. **PASS** — all checks passed or were skipped.

    Args:
        check_results: Ordered list of :class:`ReleaseCheckResult` instances
                       produced by the ``release-preflight`` pipeline.

    Returns:
        A 2-tuple of ``(disposition, reasons)`` where *disposition* is one of
        ``"PASS"``, ``"WARN"``, or ``"FAIL"`` and *reasons* is a list of
        human-readable explanation strings for each non-passing check.
    """
    reasons: list[str] = []
    has_fail: bool = False
    has_warn: bool = False

    for result in check_results:
        if result.status == "FAIL" and result.severity == "error":
            has_fail = True
            reasons.append(
                f"{result.rule_id} {result.name}: FAIL (error) — "
                f"{len(result.findings)} finding(s)"
            )
        elif result.status == "FAIL" and result.severity == "warning":
            has_warn = True
            reasons.append(
                f"{result.rule_id} {result.name}: FAIL (warning) — "
                f"{len(result.findings)} finding(s)"
            )
        elif result.status == "WARN":
            has_warn = True
            reasons.append(
                f"{result.rule_id} {result.name}: WARN ({result.severity}) — "
                f"{len(result.findings)} finding(s)"
            )

    if has_fail:
        return "FAIL", reasons
    if has_warn:
        return "WARN", reasons
    return "PASS", reasons


# ---------------------------------------------------------------------------
# Summary generation
# ---------------------------------------------------------------------------


def _generate_summary_md(pack: ReleaseEvidencePack) -> str:
    """Render a human-readable Markdown summary of the evidence pack.

    The summary includes:
    - Run metadata (run ID, artefact type, path, SHA-256, disposition).
    - Artefact inventory table (file count, total size).
    - Per-check results table.
    - Disposition reasons list for non-PASS outcomes.

    Args:
        pack: The completed :class:`ReleaseEvidencePack` to summarise.

    Returns:
        A Markdown string suitable for writing to ``summary.md``.
    """
    lines: list[str] = [
        "# Release Preflight Evidence Summary",
        "",
        f"- **Schema Version**: {pack.schema_version}",
        f"- **Run ID**: {pack.run_id}",
        f"- **Artefact Type**: {pack.artefact_type}",
        f"- **Artefact Path**: {pack.artefact_path}",
        f"- **Artefact SHA-256**: {pack.artefact_sha256}",
        f"- **Disposition**: {pack.disposition}",
        f"- **Created**: {pack.created_utc}",
    ]

    if pack.baseline_artefact_path:
        lines.append(f"- **Baseline**: {pack.baseline_artefact_path}")

    # Inventory summary table
    lines.extend(["", "## Artefact Inventory", ""])
    inv = pack.inventory
    file_count = len(inv.get("files", []))
    total_size = sum(f.get("size", 0) for f in inv.get("files", []))
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| File count | {file_count} |")
    lines.append(f"| Total size (bytes) | {total_size} |")

    # Check results table
    lines.extend(["", "## Check Results", ""])
    lines.append("| Rule ID | Check | Status | Severity | Findings | Files Checked | Time (s) |")
    lines.append("|---------|-------|--------|----------|----------|---------------|----------|")
    for r in pack.check_results:
        lines.append(
            f"| {r.rule_id} | {r.name} | {r.status} | {r.severity} "
            f"| {len(r.findings)} | {r.files_checked} | {r.elapsed_s:.2f} |"
        )

    # Disposition reasons
    if pack.disposition_reasons:
        lines.extend(["", "## Disposition Reasons", ""])
        for reason in pack.disposition_reasons:
            lines.append(f"- {reason}")

    # Premium capability state summary
    lines.extend(["", "## Capability State", ""])
    cs = pack.capability_state
    premium_enabled = cs.get("premium_capabilities_enabled", False)
    premium_installed = cs.get("premium_package_installed", False)
    lines.append(f"- Premium installed: {premium_installed}")
    lines.append(f"- Premium enabled: {premium_enabled}")
    available = cs.get("available_premium_hooks", [])
    if available:
        lines.append(f"- Available hooks: {', '.join(available)}")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Evidence writer
# ---------------------------------------------------------------------------


def write_release_evidence(
    pack: ReleaseEvidencePack,
    output_dir: Path,
) -> Path:
    """Write the release evidence pack to disk as JSON + summary.md.

    Creates *output_dir* (and any missing parents) if it does not exist.
    Two files are written:

    - ``evidence.json`` — complete serialised :class:`ReleaseEvidencePack`.
    - ``summary.md`` — human-readable Markdown summary with inventory table
      and check-results table.

    The evidence directory convention is::

        .saturnday/evidence/release/{run_id}/

    Callers are responsible for constructing an appropriate *output_dir* from
    the run ID; this function does not enforce the convention.

    Args:
        pack:       The :class:`ReleaseEvidencePack` to persist.
        output_dir: Directory path where evidence files will be written.
                    Created automatically if absent.

    Returns:
        The resolved absolute path to *output_dir* after writing.

    Raises:
        OSError: If the directory cannot be created or files cannot be written.
    """
    output_dir = Path(output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.debug("Writing release evidence to %s", output_dir)

    # Serialise the pack.  ReleaseCheckResult instances are converted manually
    # so that we keep full type safety without importing dataclasses.asdict
    # inside the writer's hot path.
    def _serialise_check(r: ReleaseCheckResult) -> dict[str, Any]:
        return {
            "name": r.name,
            "rule_id": r.rule_id,
            "status": r.status,
            "severity": r.severity,
            "findings": r.findings,
            "files_checked": r.files_checked,
            "elapsed_s": r.elapsed_s,
        }

    evidence_dict: dict[str, Any] = {
        "schema_version": pack.schema_version,
        "run_id": pack.run_id,
        "artefact_type": pack.artefact_type,
        "artefact_path": pack.artefact_path,
        "artefact_sha256": pack.artefact_sha256,
        "inventory": pack.inventory,
        "check_results": [_serialise_check(r) for r in pack.check_results],
        "disposition": pack.disposition,
        "disposition_reasons": pack.disposition_reasons,
        "baseline_artefact_path": pack.baseline_artefact_path,
        "release_diff": pack.release_diff,
        "capability_state": pack.capability_state,
        "created_utc": pack.created_utc,
    }

    evidence_path = output_dir / "evidence.json"
    evidence_path.write_text(json.dumps(evidence_dict, indent=2) + "\n", encoding="utf-8")
    logger.info("Release evidence written: %s", evidence_path)

    summary_path = output_dir / "summary.md"
    summary_path.write_text(_generate_summary_md(pack), encoding="utf-8")
    logger.debug("Release evidence summary written: %s", summary_path)

    return output_dir


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "RELEASE_SCHEMA_VERSION",
    "EVIDENCE_DIR_RELEASE",
    "ReleaseCheckResult",
    "ReleaseEvidencePack",
    "generate_release_run_id",
    "compute_release_disposition",
    "write_release_evidence",
]
